### ISSUE TITLE
添加快遞公司 auto-complete

### ISSUE THREAD

**Issue by tpnonthealps** [fython/ExpressHelper#2]
添加快遞單時，快遞公司一列應添加 auto-complete，這將是十分便利的。同時 app 應自動將繁體轉換成簡體(不必在介面層更新)，在提交時將簡體提交，這也是十分便利的。或者 auto-complete 識別繁體，但綁定的是簡體數據，也可以實現這個效果。

**Comment by Harry-Chen** [comment]
感谢支持，这个功能其实已经在开发日程上了

发自我的 iPad

在 2015-3-14，23:18，Toby Cao notifications@github.com 写道：
